package domain;
// Generated 10 May, 2017 2:09:41 PM by Hibernate Tools 4.3.1



/**
 * Aspost generated by hbm2java
 */
public class Aspost  implements java.io.Serializable {


     private String asid;
     private String uname;
     private String astmt;

    public Aspost() {
    }

	
    public Aspost(String asid) {
        this.asid = asid;
    }
    public Aspost(String asid, String uname, String astmt) {
       this.asid = asid;
       this.uname = uname;
       this.astmt = astmt;
    }
   
    public String getAsid() {
        return this.asid;
    }
    
    public void setAsid(String asid) {
        this.asid = asid;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getAstmt() {
        return this.astmt;
    }
    
    public void setAstmt(String astmt) {
        this.astmt = astmt;
    }




}


