package domain;
// Generated 10 May, 2017 2:09:41 PM by Hibernate Tools 4.3.1



/**
 * Useroep generated by hbm2java
 */
public class Useroep  implements java.io.Serializable {


     private String uname;
     private String password;
     private Boolean faculty;

    public Useroep() {
    }

	
    public Useroep(String uname) {
        this.uname = uname;
    }
    public Useroep(String uname, String password, Boolean faculty) {
       this.uname = uname;
       this.password = password;
       this.faculty = faculty;
    }
   
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Boolean faculty) {
        this.faculty = faculty;
    }




}


